//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENSConsoleApp.ENSProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportedDeliveryMode", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    [System.SerializableAttribute()]
    public partial class SupportedDeliveryMode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportedDialect", Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    [System.SerializableAttribute()]
    public partial class SupportedDialect : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", ConfigurationName="ENSProxy.EventSource")]
    public interface EventSource {
        
        // CODEGEN: Generating message contract since the operation SubscribeOp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/08/eventing/EventSource/SubscribeOpRequest", ReplyAction="http://schemas.xmlsoap.org/ws/2004/08/eventing/EventSource/SubscribeOpResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ENSConsoleApp.ENSProxy.SupportedDeliveryMode), Action="http://schemas.xmlsoap.org/ws/2004/08/eventing/EventSource/SubscribeOpSupportedDe" +
            "liveryMode", Name="SupportedDeliveryMode")]
        [System.ServiceModel.FaultContractAttribute(typeof(ENSConsoleApp.ENSProxy.SupportedDialect), Action="http://schemas.xmlsoap.org/ws/2004/08/eventing/EventSource/SubscribeOpSupportedDi" +
            "alect", Name="SupportedDialect")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ENSConsoleApp.ENSProxy.SubscribeResponseMsg SubscribeOp(ENSConsoleApp.ENSProxy.SubscribeMsg request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class Subscribe : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EndpointReferenceType endToField;
        
        private DeliveryType deliveryField;
        
        private ExpirationType expiresField;
        
        private FilterType filterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EndpointReferenceType EndTo {
            get {
                return this.endToField;
            }
            set {
                this.endToField = value;
                this.RaisePropertyChanged("EndTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DeliveryType Delivery {
            get {
                return this.deliveryField;
            }
            set {
                this.deliveryField = value;
                this.RaisePropertyChanged("Delivery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ExpirationType Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public FilterType Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("Filter");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class EndpointReferenceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AttributedURI addressField;
        
        private ReferencePropertiesType referencePropertiesField;
        
        private ReferenceParametersType referenceParametersField;
        
        private AttributedQName portTypeField;
        
        private ServiceNameType serviceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AttributedURI Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ReferencePropertiesType ReferenceProperties {
            get {
                return this.referencePropertiesField;
            }
            set {
                this.referencePropertiesField = value;
                this.RaisePropertyChanged("ReferenceProperties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ReferenceParametersType ReferenceParameters {
            get {
                return this.referenceParametersField;
            }
            set {
                this.referenceParametersField = value;
                this.RaisePropertyChanged("ReferenceParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AttributedQName PortType {
            get {
                return this.portTypeField;
            }
            set {
                this.portTypeField = value;
                this.RaisePropertyChanged("PortType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ServiceNameType ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("ServiceName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class AttributedURI : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class InternalSubscriptionManager : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EndpointReferenceType endpointAddressField;
        
        private Identifier identifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EndpointReferenceType EndpointAddress {
            get {
                return this.endpointAddressField;
            }
            set {
                this.endpointAddressField = value;
                this.RaisePropertyChanged("EndpointAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Identifier Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aircominternational.com/contract/ENS/Data/2009/10")]
    public partial class Identifier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class Subscription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isReadOnlyField;
        
        private InternalSubscriptionManager managerField;
        
        private EndpointReferenceType endToField;
        
        private DeliveryType deliveryField;
        
        private System.DateTime expiresField;
        
        private XPathMessageFilter filterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsReadOnly {
            get {
                return this.isReadOnlyField;
            }
            set {
                this.isReadOnlyField = value;
                this.RaisePropertyChanged("IsReadOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public InternalSubscriptionManager Manager {
            get {
                return this.managerField;
            }
            set {
                this.managerField = value;
                this.RaisePropertyChanged("Manager");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public EndpointReferenceType EndTo {
            get {
                return this.endToField;
            }
            set {
                this.endToField = value;
                this.RaisePropertyChanged("EndTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DeliveryType Delivery {
            get {
                return this.deliveryField;
            }
            set {
                this.deliveryField = value;
                this.RaisePropertyChanged("Delivery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public XPathMessageFilter Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("Filter");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class DeliveryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EndpointReferenceType notifyToField;
        
        private string modeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EndpointReferenceType NotifyTo {
            get {
                return this.notifyToField;
            }
            set {
                this.notifyToField = value;
                this.RaisePropertyChanged("NotifyTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("Mode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/serviceModel/2004/05/xpathfilter/")]
    public partial class XPathMessageFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private XPathMessageFilterXPath xPathField;
        
        private int nodeQuotaField;
        
        private bool nodeQuotaFieldSpecified;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public XPathMessageFilterXPath XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
                this.RaisePropertyChanged("XPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NodeQuota {
            get {
                return this.nodeQuotaField;
            }
            set {
                this.nodeQuotaField = value;
                this.RaisePropertyChanged("NodeQuota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NodeQuotaSpecified {
            get {
                return this.nodeQuotaFieldSpecified;
            }
            set {
                this.nodeQuotaFieldSpecified = value;
                this.RaisePropertyChanged("NodeQuotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/serviceModel/2004/05/xpathfilter/")]
    public partial class XPathMessageFilterXPath : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dialectField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Dialect {
            get {
                return this.dialectField;
            }
            set {
                this.dialectField = value;
                this.RaisePropertyChanged("Dialect");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class FilterType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private XPathMessageFilter filterField;
        
        private string dialectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public XPathMessageFilter Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("Filter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Dialect {
            get {
                return this.dialectField;
            }
            set {
                this.dialectField = value;
                this.RaisePropertyChanged("Dialect");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class ExpirationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class ServiceNameType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string portNameField;
        
        private System.Xml.XmlQualifiedName valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string PortName {
            get {
                return this.portNameField;
            }
            set {
                this.portNameField = value;
                this.RaisePropertyChanged("PortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.Xml.XmlQualifiedName Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class AttributedQName : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlQualifiedName valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.Xml.XmlQualifiedName Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class ReferenceParametersType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Identifier identifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Identifier Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class ReferencePropertiesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class SubscribeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EndpointReferenceType subscriptionManagerField;
        
        private ExpirationType expiresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EndpointReferenceType SubscriptionManager {
            get {
                return this.subscriptionManagerField;
            }
            set {
                this.subscriptionManagerField = value;
                this.RaisePropertyChanged("SubscriptionManager");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ExpirationType Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubscribeMsg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", Order=0)]
        public ENSConsoleApp.ENSProxy.Subscribe Subscribe;
        
        public SubscribeMsg() {
        }
        
        public SubscribeMsg(ENSConsoleApp.ENSProxy.Subscribe Subscribe) {
            this.Subscribe = Subscribe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubscribeResponseMsg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", Order=0)]
        public ENSConsoleApp.ENSProxy.SubscribeResponse SubscribeResponse;
        
        public SubscribeResponseMsg() {
        }
        
        public SubscribeResponseMsg(ENSConsoleApp.ENSProxy.SubscribeResponse SubscribeResponse) {
            this.SubscribeResponse = SubscribeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventSourceChannel : ENSConsoleApp.ENSProxy.EventSource, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventSourceClient : System.ServiceModel.ClientBase<ENSConsoleApp.ENSProxy.EventSource>, ENSConsoleApp.ENSProxy.EventSource {
        
        public EventSourceClient() {
        }
        
        public EventSourceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventSourceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventSourceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventSourceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ENSConsoleApp.ENSProxy.SubscribeResponseMsg ENSConsoleApp.ENSProxy.EventSource.SubscribeOp(ENSConsoleApp.ENSProxy.SubscribeMsg request) {
            return base.Channel.SubscribeOp(request);
        }
        
        public ENSConsoleApp.ENSProxy.SubscribeResponse SubscribeOp(ENSConsoleApp.ENSProxy.Subscribe Subscribe) {
            ENSConsoleApp.ENSProxy.SubscribeMsg inValue = new ENSConsoleApp.ENSProxy.SubscribeMsg();
            inValue.Subscribe = Subscribe;
            ENSConsoleApp.ENSProxy.SubscribeResponseMsg retVal = ((ENSConsoleApp.ENSProxy.EventSource)(this)).SubscribeOp(inValue);
            return retVal.SubscribeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", ConfigurationName="ENSProxy.SubscriptionManager")]
    public interface SubscriptionManager {
        
        // CODEGEN: Generating message contract since the operation RenewOp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/08/eventing/SubscriptionManager/RenewOpRequest" +
            "", ReplyAction="http://schemas.xmlsoap.org/ws/2004/08/eventing/SubscriptionManager/RenewOpRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ENSConsoleApp.ENSProxy.RenewResponseMsg RenewOp(ENSConsoleApp.ENSProxy.RenewMsg request);
        
        // CODEGEN: Generating message contract since the operation GetStatusOp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/08/eventing/SubscriptionManager/GetStatusOpReq" +
            "uest", ReplyAction="http://schemas.xmlsoap.org/ws/2004/08/eventing/SubscriptionManager/GetStatusOpRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ENSConsoleApp.ENSProxy.GetStatusResponseMsg GetStatusOp(ENSConsoleApp.ENSProxy.GetStatusMsg request);
        
        // CODEGEN: Generating message contract since the operation UnsubscribeOp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/08/eventing/SubscriptionManager/UnsubscribeOpR" +
            "equest", ReplyAction="http://schemas.xmlsoap.org/ws/2004/08/eventing/SubscriptionManager/UnsubscribeOpR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ENSConsoleApp.ENSProxy.UnsubscribeResponseMsg UnsubscribeOp(ENSConsoleApp.ENSProxy.UnsubscribeMsg request);
        
        // CODEGEN: Generating message contract since the operation GetSubscriptionListOp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.aircominternational.com/contract/ENS/2010/10/SubscriptionManager/GetSu" +
            "bscriptionListOpRequest", ReplyAction="http://www.aircominternational.com/contract/ENS/2010/10/SubscriptionManager/GetSu" +
            "bscriptionListOpResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ENSConsoleApp.ENSProxy.GetSubscriptionListResponseMsg GetSubscriptionListOp(ENSConsoleApp.ENSProxy.GetSubscriptionListMsg request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class Renew : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExpirationType expiresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExpirationType Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class RenewResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExpirationType expiresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExpirationType Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RenewMsg {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
        public ENSConsoleApp.ENSProxy.Identifier Identifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", Order=0)]
        public ENSConsoleApp.ENSProxy.Renew Renew;
        
        public RenewMsg() {
        }
        
        public RenewMsg(ENSConsoleApp.ENSProxy.Identifier Identifier, ENSConsoleApp.ENSProxy.Renew Renew) {
            this.Identifier = Identifier;
            this.Renew = Renew;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RenewResponseMsg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", Order=0)]
        public ENSConsoleApp.ENSProxy.RenewResponse RenewResponse;
        
        public RenewResponseMsg() {
        }
        
        public RenewResponseMsg(ENSConsoleApp.ENSProxy.RenewResponse RenewResponse) {
            this.RenewResponse = RenewResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class GetStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class GetStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExpirationType expiresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExpirationType Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusMsg {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
        public ENSConsoleApp.ENSProxy.Identifier Identifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", Order=0)]
        public ENSConsoleApp.ENSProxy.GetStatus GetStatus;
        
        public GetStatusMsg() {
        }
        
        public GetStatusMsg(ENSConsoleApp.ENSProxy.Identifier Identifier, ENSConsoleApp.ENSProxy.GetStatus GetStatus) {
            this.Identifier = Identifier;
            this.GetStatus = GetStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponseMsg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", Order=0)]
        public ENSConsoleApp.ENSProxy.GetStatusResponse GetStatusResponse;
        
        public GetStatusResponseMsg() {
        }
        
        public GetStatusResponseMsg(ENSConsoleApp.ENSProxy.GetStatusResponse GetStatusResponse) {
            this.GetStatusResponse = GetStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class Unsubscribe : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnsubscribeMsg {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
        public ENSConsoleApp.ENSProxy.Identifier Identifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", Order=0)]
        public ENSConsoleApp.ENSProxy.Unsubscribe Unsubscribe;
        
        public UnsubscribeMsg() {
        }
        
        public UnsubscribeMsg(ENSConsoleApp.ENSProxy.Identifier Identifier, ENSConsoleApp.ENSProxy.Unsubscribe Unsubscribe) {
            this.Identifier = Identifier;
            this.Unsubscribe = Unsubscribe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnsubscribeResponseMsg {
        
        public UnsubscribeResponseMsg() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class SubscriptionsList : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing")]
    public partial class SubscriptionsListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Subscription[] subscriptionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Subscription[] Subscriptions {
            get {
                return this.subscriptionsField;
            }
            set {
                this.subscriptionsField = value;
                this.RaisePropertyChanged("Subscriptions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubscriptionListMsg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", Order=0)]
        public ENSConsoleApp.ENSProxy.SubscriptionsList SubscriptionsList;
        
        public GetSubscriptionListMsg() {
        }
        
        public GetSubscriptionListMsg(ENSConsoleApp.ENSProxy.SubscriptionsList SubscriptionsList) {
            this.SubscriptionsList = SubscriptionsList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubscriptionListResponseMsg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/eventing", Order=0)]
        public ENSConsoleApp.ENSProxy.SubscriptionsListResponse SubscriptionsListResponse;
        
        public GetSubscriptionListResponseMsg() {
        }
        
        public GetSubscriptionListResponseMsg(ENSConsoleApp.ENSProxy.SubscriptionsListResponse SubscriptionsListResponse) {
            this.SubscriptionsListResponse = SubscriptionsListResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubscriptionManagerChannel : ENSConsoleApp.ENSProxy.SubscriptionManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubscriptionManagerClient : System.ServiceModel.ClientBase<ENSConsoleApp.ENSProxy.SubscriptionManager>, ENSConsoleApp.ENSProxy.SubscriptionManager {
        
        public SubscriptionManagerClient() {
        }
        
        public SubscriptionManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubscriptionManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriptionManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriptionManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ENSConsoleApp.ENSProxy.RenewResponseMsg ENSConsoleApp.ENSProxy.SubscriptionManager.RenewOp(ENSConsoleApp.ENSProxy.RenewMsg request) {
            return base.Channel.RenewOp(request);
        }
        
        public ENSConsoleApp.ENSProxy.RenewResponse RenewOp(ENSConsoleApp.ENSProxy.Identifier Identifier, ENSConsoleApp.ENSProxy.Renew Renew) {
            ENSConsoleApp.ENSProxy.RenewMsg inValue = new ENSConsoleApp.ENSProxy.RenewMsg();
            inValue.Identifier = Identifier;
            inValue.Renew = Renew;
            ENSConsoleApp.ENSProxy.RenewResponseMsg retVal = ((ENSConsoleApp.ENSProxy.SubscriptionManager)(this)).RenewOp(inValue);
            return retVal.RenewResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ENSConsoleApp.ENSProxy.GetStatusResponseMsg ENSConsoleApp.ENSProxy.SubscriptionManager.GetStatusOp(ENSConsoleApp.ENSProxy.GetStatusMsg request) {
            return base.Channel.GetStatusOp(request);
        }
        
        public ENSConsoleApp.ENSProxy.GetStatusResponse GetStatusOp(ENSConsoleApp.ENSProxy.Identifier Identifier, ENSConsoleApp.ENSProxy.GetStatus GetStatus) {
            ENSConsoleApp.ENSProxy.GetStatusMsg inValue = new ENSConsoleApp.ENSProxy.GetStatusMsg();
            inValue.Identifier = Identifier;
            inValue.GetStatus = GetStatus;
            ENSConsoleApp.ENSProxy.GetStatusResponseMsg retVal = ((ENSConsoleApp.ENSProxy.SubscriptionManager)(this)).GetStatusOp(inValue);
            return retVal.GetStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ENSConsoleApp.ENSProxy.UnsubscribeResponseMsg ENSConsoleApp.ENSProxy.SubscriptionManager.UnsubscribeOp(ENSConsoleApp.ENSProxy.UnsubscribeMsg request) {
            return base.Channel.UnsubscribeOp(request);
        }
        
        public void UnsubscribeOp(ENSConsoleApp.ENSProxy.Identifier Identifier, ENSConsoleApp.ENSProxy.Unsubscribe Unsubscribe) {
            ENSConsoleApp.ENSProxy.UnsubscribeMsg inValue = new ENSConsoleApp.ENSProxy.UnsubscribeMsg();
            inValue.Identifier = Identifier;
            inValue.Unsubscribe = Unsubscribe;
            ENSConsoleApp.ENSProxy.UnsubscribeResponseMsg retVal = ((ENSConsoleApp.ENSProxy.SubscriptionManager)(this)).UnsubscribeOp(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ENSConsoleApp.ENSProxy.GetSubscriptionListResponseMsg ENSConsoleApp.ENSProxy.SubscriptionManager.GetSubscriptionListOp(ENSConsoleApp.ENSProxy.GetSubscriptionListMsg request) {
            return base.Channel.GetSubscriptionListOp(request);
        }
        
        public ENSConsoleApp.ENSProxy.SubscriptionsListResponse GetSubscriptionListOp(ENSConsoleApp.ENSProxy.SubscriptionsList SubscriptionsList) {
            ENSConsoleApp.ENSProxy.GetSubscriptionListMsg inValue = new ENSConsoleApp.ENSProxy.GetSubscriptionListMsg();
            inValue.SubscriptionsList = SubscriptionsList;
            ENSConsoleApp.ENSProxy.GetSubscriptionListResponseMsg retVal = ((ENSConsoleApp.ENSProxy.SubscriptionManager)(this)).GetSubscriptionListOp(inValue);
            return retVal.SubscriptionsListResponse;
        }
    }
}
