//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace NetPlanClient.BLL.AirComSvr {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AirComServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AirComService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateTaskOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AirComService() {
            this.Url = global::NetPlanClient.BLL.Properties.Settings.Default.NetPlanClient_BLL_AirComSvr_AirComService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateTaskCompletedEventHandler CreateTaskCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateTask(PLAData Data) {
            this.Invoke("CreateTask", new object[] {
                        Data});
        }
        
        /// <remarks/>
        public void CreateTaskAsync(PLAData Data) {
            this.CreateTaskAsync(Data, null);
        }
        
        /// <remarks/>
        public void CreateTaskAsync(PLAData Data, object userState) {
            if ((this.CreateTaskOperationCompleted == null)) {
                this.CreateTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTaskOperationCompleted);
            }
            this.InvokeAsync("CreateTask", new object[] {
                        Data}, this.CreateTaskOperationCompleted, userState);
        }
        
        private void OnCreateTaskOperationCompleted(object arg) {
            if ((this.CreateTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTaskCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PLAData {
        
        private AirComLTENodeBaseInfo baseInfoField;
        
        private CellSector[] cellSectorsField;
        
        private string savedirField;
        
        private string projectNameField;
        
        private GeoRegion regionBoundField;
        
        /// <remarks/>
        public AirComLTENodeBaseInfo BaseInfo {
            get {
                return this.baseInfoField;
            }
            set {
                this.baseInfoField = value;
            }
        }
        
        /// <remarks/>
        public CellSector[] CellSectors {
            get {
                return this.cellSectorsField;
            }
            set {
                this.cellSectorsField = value;
            }
        }
        
        /// <remarks/>
        public string Savedir {
            get {
                return this.savedirField;
            }
            set {
                this.savedirField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
            }
        }
        
        /// <remarks/>
        public GeoRegion RegionBound {
            get {
                return this.regionBoundField;
            }
            set {
                this.regionBoundField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AirComLTENodeBaseInfo {
        
        private string cityNameField;
        
        private string stationIdField;
        
        private string stationAliasField;
        
        private double lngField;
        
        private double latField;
        
        private EnumStationType stationTypeField;
        
        private EnumSaveType saveTypeField;
        
        private EnumCoverType coverTypeField;
        
        private int planPrjIDField;
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string StationId {
            get {
                return this.stationIdField;
            }
            set {
                this.stationIdField = value;
            }
        }
        
        /// <remarks/>
        public string StationAlias {
            get {
                return this.stationAliasField;
            }
            set {
                this.stationAliasField = value;
            }
        }
        
        /// <remarks/>
        public double Lng {
            get {
                return this.lngField;
            }
            set {
                this.lngField = value;
            }
        }
        
        /// <remarks/>
        public double Lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        public EnumStationType StationType {
            get {
                return this.stationTypeField;
            }
            set {
                this.stationTypeField = value;
            }
        }
        
        /// <remarks/>
        public EnumSaveType SaveType {
            get {
                return this.saveTypeField;
            }
            set {
                this.saveTypeField = value;
            }
        }
        
        /// <remarks/>
        public EnumCoverType CoverType {
            get {
                return this.coverTypeField;
            }
            set {
                this.coverTypeField = value;
            }
        }
        
        /// <remarks/>
        public int PlanPrjID {
            get {
                return this.planPrjIDField;
            }
            set {
                this.planPrjIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EnumStationType {
        
        /// <remarks/>
        Planning,
        
        /// <remarks/>
        Extant,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EnumSaveType {
        
        /// <remarks/>
        Save,
        
        /// <remarks/>
        Delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EnumCoverType {
        
        /// <remarks/>
        Outdoor,
        
        /// <remarks/>
        Indoor,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GeoRegion {
        
        private double eastMinField;
        
        private double eastmaxField;
        
        private double northMinField;
        
        private double northMaxField;
        
        /// <remarks/>
        public double EastMin {
            get {
                return this.eastMinField;
            }
            set {
                this.eastMinField = value;
            }
        }
        
        /// <remarks/>
        public double Eastmax {
            get {
                return this.eastmaxField;
            }
            set {
                this.eastmaxField = value;
            }
        }
        
        /// <remarks/>
        public double NorthMin {
            get {
                return this.northMinField;
            }
            set {
                this.northMinField = value;
            }
        }
        
        /// <remarks/>
        public double NorthMax {
            get {
                return this.northMaxField;
            }
            set {
                this.northMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AirComLocationType {
        
        private double longitudeFieldField;
        
        private double latitudeField;
        
        private bool longitudeSpecified1Field;
        
        /// <remarks/>
        public double LongitudeField {
            get {
                return this.longitudeFieldField;
            }
            set {
                this.longitudeFieldField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("LongitudeSpecified")]
        public bool LongitudeSpecified1 {
            get {
                return this.longitudeSpecified1Field;
            }
            set {
                this.longitudeSpecified1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AirComAntennaType {
        
        private int _AzimuthField;
        
        private double _HeightField;
        
        private double _MechanicalDownTiltField;
        
        private double _ElectricalDownTiltField;
        
        private AirComLocationType locationField;
        
        private double _PowerField;
        
        private double _burthenField;
        
        private int sectorIdField;
        
        private string antennaTypeNameField;
        
        private int azimuthField;
        
        private double heightField;
        
        private double mechanicalDownTiltField;
        
        private double electricalDownTiltField;
        
        private double powerField;
        
        private double burthenField;
        
        private string modelTypeField;
        
        private string carrierAliasField;
        
        private int carrierIdField;
        
        private double radiusKmField;
        
        private double resolutionMetresField;
        
        /// <remarks/>
        public int _Azimuth {
            get {
                return this._AzimuthField;
            }
            set {
                this._AzimuthField = value;
            }
        }
        
        /// <remarks/>
        public double _Height {
            get {
                return this._HeightField;
            }
            set {
                this._HeightField = value;
            }
        }
        
        /// <remarks/>
        public double _MechanicalDownTilt {
            get {
                return this._MechanicalDownTiltField;
            }
            set {
                this._MechanicalDownTiltField = value;
            }
        }
        
        /// <remarks/>
        public double _ElectricalDownTilt {
            get {
                return this._ElectricalDownTiltField;
            }
            set {
                this._ElectricalDownTiltField = value;
            }
        }
        
        /// <remarks/>
        public AirComLocationType Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public double _Power {
            get {
                return this._PowerField;
            }
            set {
                this._PowerField = value;
            }
        }
        
        /// <remarks/>
        public double _burthen {
            get {
                return this._burthenField;
            }
            set {
                this._burthenField = value;
            }
        }
        
        /// <remarks/>
        public int SectorId {
            get {
                return this.sectorIdField;
            }
            set {
                this.sectorIdField = value;
            }
        }
        
        /// <remarks/>
        public string AntennaTypeName {
            get {
                return this.antennaTypeNameField;
            }
            set {
                this.antennaTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public int Azimuth {
            get {
                return this.azimuthField;
            }
            set {
                this.azimuthField = value;
            }
        }
        
        /// <remarks/>
        public double Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public double MechanicalDownTilt {
            get {
                return this.mechanicalDownTiltField;
            }
            set {
                this.mechanicalDownTiltField = value;
            }
        }
        
        /// <remarks/>
        public double ElectricalDownTilt {
            get {
                return this.electricalDownTiltField;
            }
            set {
                this.electricalDownTiltField = value;
            }
        }
        
        /// <remarks/>
        public double Power {
            get {
                return this.powerField;
            }
            set {
                this.powerField = value;
            }
        }
        
        /// <remarks/>
        public double Burthen {
            get {
                return this.burthenField;
            }
            set {
                this.burthenField = value;
            }
        }
        
        /// <remarks/>
        public string ModelType {
            get {
                return this.modelTypeField;
            }
            set {
                this.modelTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierAlias {
            get {
                return this.carrierAliasField;
            }
            set {
                this.carrierAliasField = value;
            }
        }
        
        /// <remarks/>
        public int CarrierId {
            get {
                return this.carrierIdField;
            }
            set {
                this.carrierIdField = value;
            }
        }
        
        /// <remarks/>
        public double RadiusKm {
            get {
                return this.radiusKmField;
            }
            set {
                this.radiusKmField = value;
            }
        }
        
        /// <remarks/>
        public double ResolutionMetres {
            get {
                return this.resolutionMetresField;
            }
            set {
                this.resolutionMetresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CellSector {
        
        private int cellIDField;
        
        private AirComAntennaType[] antennersField;
        
        /// <remarks/>
        public int CellID {
            get {
                return this.cellIDField;
            }
            set {
                this.cellIDField = value;
            }
        }
        
        /// <remarks/>
        public AirComAntennaType[] Antenners {
            get {
                return this.antennersField;
            }
            set {
                this.antennersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CreateTaskCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591