//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace NetPlanClient.AirComService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AirComServiceSoap", Namespace="http://AircomPlan.com")]
    public partial class AirComService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateTaskOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateTaskByXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloWordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AirComService() {
            this.Url = global::NetPlanClient.Properties.Settings.Default.NetPlanClient_AirComService_AirComService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateTaskCompletedEventHandler CreateTaskCompleted;
        
        /// <remarks/>
        public event CreateTaskByXMLCompletedEventHandler CreateTaskByXMLCompleted;
        
        /// <remarks/>
        public event HelloWordCompletedEventHandler HelloWordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AircomPlan.com/CreateTask", RequestNamespace="http://AircomPlan.com", ResponseNamespace="http://AircomPlan.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateTask(PLAData Data) {
            object[] results = this.Invoke("CreateTask", new object[] {
                        Data});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateTaskAsync(PLAData Data) {
            this.CreateTaskAsync(Data, null);
        }
        
        /// <remarks/>
        public void CreateTaskAsync(PLAData Data, object userState) {
            if ((this.CreateTaskOperationCompleted == null)) {
                this.CreateTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTaskOperationCompleted);
            }
            this.InvokeAsync("CreateTask", new object[] {
                        Data}, this.CreateTaskOperationCompleted, userState);
        }
        
        private void OnCreateTaskOperationCompleted(object arg) {
            if ((this.CreateTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTaskCompleted(this, new CreateTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AircomPlan.com/CreateTaskByXML", RequestNamespace="http://AircomPlan.com", ResponseNamespace="http://AircomPlan.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateTaskByXML(string Data) {
            object[] results = this.Invoke("CreateTaskByXML", new object[] {
                        Data});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateTaskByXMLAsync(string Data) {
            this.CreateTaskByXMLAsync(Data, null);
        }
        
        /// <remarks/>
        public void CreateTaskByXMLAsync(string Data, object userState) {
            if ((this.CreateTaskByXMLOperationCompleted == null)) {
                this.CreateTaskByXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTaskByXMLOperationCompleted);
            }
            this.InvokeAsync("CreateTaskByXML", new object[] {
                        Data}, this.CreateTaskByXMLOperationCompleted, userState);
        }
        
        private void OnCreateTaskByXMLOperationCompleted(object arg) {
            if ((this.CreateTaskByXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTaskByXMLCompleted(this, new CreateTaskByXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AircomPlan.com/HelloWord", RequestNamespace="http://AircomPlan.com", ResponseNamespace="http://AircomPlan.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HelloWord() {
            object[] results = this.Invoke("HelloWord", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWordAsync() {
            this.HelloWordAsync(null);
        }
        
        /// <remarks/>
        public void HelloWordAsync(object userState) {
            if ((this.HelloWordOperationCompleted == null)) {
                this.HelloWordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWordOperationCompleted);
            }
            this.InvokeAsync("HelloWord", new object[0], this.HelloWordOperationCompleted, userState);
        }
        
        private void OnHelloWordOperationCompleted(object arg) {
            if ((this.HelloWordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWordCompleted(this, new HelloWordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://AircomPlan.com")]
    public partial class PLAData {
        
        private long workOrderField;
        
        private AirComLTENodeBaseInfo baseInfoField;
        
        private CellSector[] cellSectorsField;
        
        private string projectNameField;
        
        private double coverRadiusField;
        
        /// <remarks/>
        public long WorkOrder {
            get {
                return this.workOrderField;
            }
            set {
                this.workOrderField = value;
            }
        }
        
        /// <remarks/>
        public AirComLTENodeBaseInfo BaseInfo {
            get {
                return this.baseInfoField;
            }
            set {
                this.baseInfoField = value;
            }
        }
        
        /// <remarks/>
        public CellSector[] CellSectors {
            get {
                return this.cellSectorsField;
            }
            set {
                this.cellSectorsField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
            }
        }
        
        /// <remarks/>
        public double CoverRadius {
            get {
                return this.coverRadiusField;
            }
            set {
                this.coverRadiusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://AircomPlan.com")]
    public partial class AirComLTENodeBaseInfo {
        
        private string cityNameField;
        
        private string stationIdField;
        
        private string stationAliasField;
        
        private double lngField;
        
        private double latField;
        
        private EnumStationType stationTypeField;
        
        private EnumSaveType saveTypeField;
        
        private EnumCoverType coverTypeField;
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string StationId {
            get {
                return this.stationIdField;
            }
            set {
                this.stationIdField = value;
            }
        }
        
        /// <remarks/>
        public string StationAlias {
            get {
                return this.stationAliasField;
            }
            set {
                this.stationAliasField = value;
            }
        }
        
        /// <remarks/>
        public double Lng {
            get {
                return this.lngField;
            }
            set {
                this.lngField = value;
            }
        }
        
        /// <remarks/>
        public double Lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        public EnumStationType StationType {
            get {
                return this.stationTypeField;
            }
            set {
                this.stationTypeField = value;
            }
        }
        
        /// <remarks/>
        public EnumSaveType SaveType {
            get {
                return this.saveTypeField;
            }
            set {
                this.saveTypeField = value;
            }
        }
        
        /// <remarks/>
        public EnumCoverType CoverType {
            get {
                return this.coverTypeField;
            }
            set {
                this.coverTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://AircomPlan.com")]
    public enum EnumStationType {
        
        /// <remarks/>
        Planning,
        
        /// <remarks/>
        Extant,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://AircomPlan.com")]
    public enum EnumSaveType {
        
        /// <remarks/>
        Save,
        
        /// <remarks/>
        Delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://AircomPlan.com")]
    public enum EnumCoverType {
        
        /// <remarks/>
        Outdoor,
        
        /// <remarks/>
        Indoor,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://AircomPlan.com")]
    public partial class AirComLocationType {
        
        private double longitudeFieldField;
        
        private double latitudeField;
        
        private bool longitudeSpecified1Field;
        
        /// <remarks/>
        public double LongitudeField {
            get {
                return this.longitudeFieldField;
            }
            set {
                this.longitudeFieldField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("LongitudeSpecified")]
        public bool LongitudeSpecified1 {
            get {
                return this.longitudeSpecified1Field;
            }
            set {
                this.longitudeSpecified1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://AircomPlan.com")]
    public partial class AirComAntennaType {
        
        private AirComLocationType locationField;
        
        private string sectorIdField;
        
        private string antennaTypeNameField;
        
        private int azimuthField;
        
        private double heightField;
        
        private double mechanicalDownTiltField;
        
        private double electricalDownTiltField;
        
        private double powerField;
        
        private double burthenField;
        
        private string modelTypeField;
        
        private string carrierAliasField;
        
        private int carrierIdField;
        
        private double radiusKmField;
        
        private double resolutionMetresField;
        
        /// <remarks/>
        public AirComLocationType Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string SectorId {
            get {
                return this.sectorIdField;
            }
            set {
                this.sectorIdField = value;
            }
        }
        
        /// <remarks/>
        public string AntennaTypeName {
            get {
                return this.antennaTypeNameField;
            }
            set {
                this.antennaTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public int Azimuth {
            get {
                return this.azimuthField;
            }
            set {
                this.azimuthField = value;
            }
        }
        
        /// <remarks/>
        public double Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public double MechanicalDownTilt {
            get {
                return this.mechanicalDownTiltField;
            }
            set {
                this.mechanicalDownTiltField = value;
            }
        }
        
        /// <remarks/>
        public double ElectricalDownTilt {
            get {
                return this.electricalDownTiltField;
            }
            set {
                this.electricalDownTiltField = value;
            }
        }
        
        /// <remarks/>
        public double Power {
            get {
                return this.powerField;
            }
            set {
                this.powerField = value;
            }
        }
        
        /// <remarks/>
        public double Burthen {
            get {
                return this.burthenField;
            }
            set {
                this.burthenField = value;
            }
        }
        
        /// <remarks/>
        public string ModelType {
            get {
                return this.modelTypeField;
            }
            set {
                this.modelTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierAlias {
            get {
                return this.carrierAliasField;
            }
            set {
                this.carrierAliasField = value;
            }
        }
        
        /// <remarks/>
        public int CarrierId {
            get {
                return this.carrierIdField;
            }
            set {
                this.carrierIdField = value;
            }
        }
        
        /// <remarks/>
        public double RadiusKm {
            get {
                return this.radiusKmField;
            }
            set {
                this.radiusKmField = value;
            }
        }
        
        /// <remarks/>
        public double ResolutionMetres {
            get {
                return this.resolutionMetresField;
            }
            set {
                this.resolutionMetresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://AircomPlan.com")]
    public partial class CellSector {
        
        private int cellIDField;
        
        private AirComAntennaType[] antennersField;
        
        /// <remarks/>
        public int CellID {
            get {
                return this.cellIDField;
            }
            set {
                this.cellIDField = value;
            }
        }
        
        /// <remarks/>
        public AirComAntennaType[] Antenners {
            get {
                return this.antennersField;
            }
            set {
                this.antennersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CreateTaskCompletedEventHandler(object sender, CreateTaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CreateTaskByXMLCompletedEventHandler(object sender, CreateTaskByXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateTaskByXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateTaskByXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWordCompletedEventHandler(object sender, HelloWordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591